package pl;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int program = 6;
  public static final int function = 12;
  public static final int distinto = 42;
  public static final int tcase = 29;
  public static final int mod = 14;
  public static final int array = 19;
  public static final int coma = 30;
  public static final int igual = 32;
  public static final int tif = 22;
  public static final int begin = 7;
  public static final int real = 2;
  public static final int tint = 4;
  public static final int end = 8;
  public static final int parentesisizq = 44;
  public static final int tfor = 27;
  public static final int menos = 38;
  public static final int then = 23;
  public static final int menor = 39;
  public static final int var = 10;
  public static final int EOF = 0;
  public static final int mas = 33;
  public static final int twhile = 25;
  public static final int corcheteizq = 46;
  public static final int error = 1;
  public static final int mayor = 37;
  public static final int or = 15;
  public static final int menorigual = 40;
  public static final int por = 43;
  public static final int procedure = 11;
  public static final int punto = 3;
  public static final int telse = 24;
  public static final int dospuntos = 34;
  public static final int constnumint = 50;
  public static final int id = 48;
  public static final int of = 20;
  public static final int record = 21;
  public static final int mayorigual = 41;
  public static final int tdo = 26;
  public static final int parentesisder = 45;
  public static final int and = 16;
  public static final int not = 17;
  public static final int puntocoma = 31;
  public static final int tconst = 9;
  public static final int constnumreal = 51;
  public static final int div = 13;
  public static final int puntopunto = 35;
  public static final int asignacion = 36;
  public static final int constlit = 49;
  public static final int corcheteder = 47;
  public static final int to = 28;
  public static final int tchar = 5;
  public static final int type = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "real",
  "punto",
  "tint",
  "tchar",
  "program",
  "begin",
  "end",
  "tconst",
  "var",
  "procedure",
  "function",
  "div",
  "mod",
  "or",
  "and",
  "not",
  "type",
  "array",
  "of",
  "record",
  "tif",
  "then",
  "telse",
  "twhile",
  "tdo",
  "tfor",
  "to",
  "tcase",
  "coma",
  "puntocoma",
  "igual",
  "mas",
  "dospuntos",
  "puntopunto",
  "asignacion",
  "mayor",
  "menos",
  "menor",
  "menorigual",
  "mayorigual",
  "distinto",
  "por",
  "parentesisizq",
  "parentesisder",
  "corcheteizq",
  "corcheteder",
  "id",
  "constlit",
  "constnumint",
  "constnumreal"
  };
}

