/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/UNI/Git hub valli/Peter-Valli/PL/Listado fuente y memoria/LexicoPracticas(Grupo-4).flex</tt>
 */
class PracticaLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int constLit = 2;
  public static final int comentPar = 4;
  public static final int comentLlav = 6;
  public static final int comentParFin = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\64\1\64\1\65\1\65\1\64\22\0\1\64\3\0\1\5"+
    "\2\0\1\11\1\7\1\61\1\10\1\55\1\52\1\3\1\4\1\0"+
    "\12\2\1\56\1\53\1\57\1\54\1\60\2\0\1\30\1\6\1\41"+
    "\1\6\1\27\1\6\1\35\1\42\1\32\2\1\1\31\1\1\1\33"+
    "\3\1\1\26\1\1\1\34\6\1\1\62\1\0\1\63\1\0\1\1"+
    "\1\0\1\24\1\13\1\36\1\20\1\14\1\45\1\15\1\47\1\16"+
    "\2\1\1\50\1\25\1\17\1\23\1\21\1\1\1\22\1\37\1\40"+
    "\1\44\1\43\1\51\1\1\1\46\1\1\1\12\1\0\1\66\7\0"+
    "\1\65\u1fa2\0\1\65\1\65\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\22\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\24\1\27\1\30\1\31\1\0\1\32\1\3"+
    "\1\0\3\2\1\33\2\2\1\34\2\2\1\35\1\36"+
    "\7\2\1\37\7\2\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\0\1\2\1\46\1\2\1\47\1\50\2\2"+
    "\1\51\1\2\1\52\7\2\1\53\1\54\2\2\1\45"+
    "\1\2\1\55\4\2\1\56\2\2\1\57\1\60\1\61"+
    "\3\2\1\62\3\2\1\63\1\2\1\64\2\2\1\65"+
    "\2\2\1\66\3\2\1\67\1\2\1\70\4\2\1\71"+
    "\1\72\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0113\0\u0113\0\u0113\0\u0294"+
    "\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c"+
    "\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604"+
    "\0\u063b\0\u0113\0\u0113\0\u0113\0\u01b8\0\u0672\0\u06a9\0\u06e0"+
    "\0\u0113\0\u0113\0\u0113\0\u0717\0\u0113\0\u074e\0\u0113\0\u0113"+
    "\0\u0113\0\u0113\0\u0785\0\u0113\0\u07bc\0\u07f3\0\u082a\0\u0861"+
    "\0\u0898\0\u014a\0\u08cf\0\u0906\0\u014a\0\u093d\0\u0974\0\u014a"+
    "\0\u014a\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u014a\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u0113\0\u0113\0\u0113\0\u0113\0\u0113\0\u0785\0\u0cad\0\u0ce4"+
    "\0\u014a\0\u0d1b\0\u014a\0\u014a\0\u0d52\0\u0d89\0\u014a\0\u0dc0"+
    "\0\u014a\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u014a\0\u014a\0\u0f78\0\u0faf\0\u0cad\0\u0fe6\0\u014a\0\u101d"+
    "\0\u1054\0\u108b\0\u10c2\0\u014a\0\u10f9\0\u1130\0\u014a\0\u014a"+
    "\0\u014a\0\u1167\0\u119e\0\u11d5\0\u014a\0\u120c\0\u1243\0\u127a"+
    "\0\u014a\0\u12b1\0\u014a\0\u12e8\0\u131f\0\u014a\0\u1356\0\u138d"+
    "\0\u014a\0\u13c4\0\u13fb\0\u1432\0\u014a\0\u1469\0\u014a\0\u14a0"+
    "\0\u14d7\0\u150e\0\u1545\0\u014a\0\u014a\0\u014a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\7\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\7\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\3\7"+
    "\1\33\3\7\1\34\1\7\1\35\1\36\1\7\1\37"+
    "\1\7\1\40\3\7\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\0"+
    "\1\6\11\55\1\56\55\55\10\57\1\60\144\57\1\61"+
    "\61\62\1\61\5\62\70\0\2\7\3\0\1\7\4\0"+
    "\37\7\17\0\1\10\1\0\1\63\64\0\1\10\70\0"+
    "\1\64\64\0\1\65\1\66\2\0\1\65\20\0\2\65"+
    "\10\0\1\65\13\0\1\66\21\0\1\62\57\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\67\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\4\7\1\70\30\7\1\71\1\7"+
    "\16\0\2\7\3\0\1\7\4\0\32\7\1\72\4\7"+
    "\16\0\2\7\3\0\1\7\4\0\10\7\1\73\26\7"+
    "\16\0\2\7\3\0\1\7\4\0\3\7\1\74\4\7"+
    "\1\75\26\7\16\0\2\7\3\0\1\7\4\0\7\7"+
    "\1\76\27\7\16\0\2\7\3\0\1\7\4\0\1\7"+
    "\1\77\35\7\16\0\2\7\3\0\1\7\4\0\7\7"+
    "\1\100\22\7\1\101\4\7\16\0\2\7\3\0\1\7"+
    "\4\0\4\7\1\102\2\7\1\103\27\7\16\0\2\7"+
    "\3\0\1\7\4\0\10\7\1\104\26\7\16\0\2\7"+
    "\3\0\1\7\4\0\14\7\1\105\22\7\16\0\2\7"+
    "\3\0\1\7\4\0\20\7\1\106\16\7\16\0\2\7"+
    "\3\0\1\7\4\0\10\7\1\107\1\110\25\7\16\0"+
    "\2\7\3\0\1\7\4\0\10\7\1\111\22\7\1\112"+
    "\1\113\2\7\16\0\2\7\3\0\1\7\4\0\27\7"+
    "\1\114\7\7\16\0\2\7\3\0\1\7\4\0\11\7"+
    "\1\115\25\7\16\0\2\7\3\0\1\7\4\0\10\7"+
    "\1\116\20\7\1\117\5\7\16\0\2\7\3\0\1\7"+
    "\4\0\34\7\1\120\2\7\71\0\1\121\66\0\1\122"+
    "\3\0\1\123\62\0\1\124\76\0\1\54\13\0\1\125"+
    "\57\0\1\126\66\0\1\65\1\0\1\127\1\0\1\65"+
    "\20\0\2\65\10\0\1\65\27\0\1\65\3\0\1\65"+
    "\20\0\2\65\10\0\1\65\26\0\2\7\3\0\1\7"+
    "\4\0\2\7\1\130\34\7\16\0\2\7\3\0\1\7"+
    "\4\0\5\7\1\131\31\7\16\0\2\7\3\0\1\7"+
    "\4\0\24\7\1\132\12\7\16\0\2\7\3\0\1\7"+
    "\4\0\25\7\1\133\11\7\16\0\2\7\3\0\1\7"+
    "\4\0\30\7\1\134\6\7\16\0\2\7\3\0\1\7"+
    "\4\0\10\7\1\135\26\7\16\0\2\7\3\0\1\7"+
    "\4\0\23\7\1\136\13\7\16\0\2\7\3\0\1\7"+
    "\4\0\5\7\1\137\31\7\16\0\2\7\3\0\1\7"+
    "\4\0\7\7\1\140\27\7\16\0\2\7\3\0\1\7"+
    "\4\0\5\7\1\141\31\7\16\0\2\7\3\0\1\7"+
    "\4\0\15\7\1\142\21\7\16\0\2\7\3\0\1\7"+
    "\4\0\21\7\1\143\15\7\16\0\2\7\3\0\1\7"+
    "\4\0\4\7\1\144\32\7\16\0\2\7\3\0\1\7"+
    "\4\0\24\7\1\145\12\7\16\0\2\7\3\0\1\7"+
    "\4\0\6\7\1\146\30\7\16\0\2\7\3\0\1\7"+
    "\4\0\1\7\1\147\35\7\16\0\2\7\3\0\1\7"+
    "\4\0\15\7\1\150\21\7\16\0\2\7\3\0\1\7"+
    "\4\0\7\7\1\151\27\7\16\0\2\7\3\0\1\7"+
    "\4\0\7\7\1\152\27\7\16\0\2\7\3\0\1\7"+
    "\4\0\4\7\1\153\32\7\16\0\2\7\3\0\1\7"+
    "\4\0\3\7\1\154\33\7\17\0\1\155\3\0\1\155"+
    "\20\0\2\155\10\0\1\155\26\0\2\7\3\0\1\7"+
    "\4\0\3\7\1\156\33\7\16\0\2\7\3\0\1\7"+
    "\4\0\1\7\1\157\35\7\16\0\2\7\3\0\1\7"+
    "\4\0\2\7\1\160\20\7\1\161\13\7\16\0\2\7"+
    "\3\0\1\7\4\0\10\7\1\162\26\7\16\0\2\7"+
    "\3\0\1\7\4\0\11\7\1\163\25\7\16\0\2\7"+
    "\3\0\1\7\4\0\16\7\1\164\20\7\16\0\2\7"+
    "\3\0\1\7\4\0\14\7\1\165\22\7\16\0\2\7"+
    "\3\0\1\7\4\0\24\7\1\166\12\7\16\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\167\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\170\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\4\7\1\171\32\7\16\0\2\7"+
    "\3\0\1\7\4\0\13\7\1\172\23\7\16\0\2\7"+
    "\3\0\1\7\4\0\23\7\1\173\13\7\16\0\2\7"+
    "\3\0\1\7\4\0\35\7\1\174\1\7\16\0\2\7"+
    "\3\0\1\7\4\0\4\7\1\175\32\7\16\0\2\7"+
    "\3\0\1\7\4\0\7\7\1\176\27\7\16\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\177\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\7\7\1\200\27\7\16\0\2\7"+
    "\3\0\1\7\4\0\33\7\1\201\3\7\16\0\2\7"+
    "\3\0\1\7\4\0\22\7\1\202\14\7\16\0\2\7"+
    "\3\0\1\7\4\0\25\7\1\203\11\7\16\0\2\7"+
    "\3\0\1\7\4\0\15\7\1\204\21\7\16\0\2\7"+
    "\3\0\1\7\4\0\25\7\1\205\11\7\16\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\206\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\11\7\1\207\25\7\16\0\2\7"+
    "\3\0\1\7\4\0\5\7\1\210\31\7\16\0\2\7"+
    "\3\0\1\7\4\0\5\7\1\211\31\7\16\0\2\7"+
    "\3\0\1\7\4\0\14\7\1\212\22\7\16\0\2\7"+
    "\3\0\1\7\4\0\26\7\1\213\10\7\16\0\2\7"+
    "\3\0\1\7\4\0\3\7\1\214\33\7\16\0\2\7"+
    "\3\0\1\7\4\0\12\7\1\215\24\7\16\0\2\7"+
    "\3\0\1\7\4\0\31\7\1\216\5\7\16\0\2\7"+
    "\3\0\1\7\4\0\13\7\1\217\23\7\16\0\2\7"+
    "\3\0\1\7\4\0\21\7\1\220\15\7\16\0\2\7"+
    "\3\0\1\7\4\0\10\7\1\221\26\7\16\0\2\7"+
    "\3\0\1\7\4\0\7\7\1\222\27\7\16\0\2\7"+
    "\3\0\1\7\4\0\14\7\1\223\22\7\16\0\2\7"+
    "\3\0\1\7\4\0\4\7\1\224\32\7\16\0\2\7"+
    "\3\0\1\7\4\0\1\7\1\225\35\7\16\0\2\7"+
    "\3\0\1\7\4\0\13\7\1\226\23\7\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5500];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\6\1\3\11\22\1\3\11\4\1\3\11"+
    "\1\1\1\11\1\1\4\11\1\0\1\11\1\1\1\0"+
    "\32\1\5\11\1\1\1\0\77\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
private String litconst;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PracticaLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 202) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Lexical Error: \"" + yytext()+ "\" line: "+(yyline+1)+" column: "+(yycolumn+1)+", do not belong to the alphabet");
            }
          case 60: break;
          case 2: 
            { return new java_cup.runtime.Symbol(sym.id,yyline+1,yycolumn+1,yytext());
            }
          case 61: break;
          case 3: 
            { return new java_cup.runtime.Symbol(sym.constnumint,yyline+1,yycolumn+1,yytext());
            }
          case 62: break;
          case 4: 
            { return new java_cup.runtime.Symbol(sym.menos,yyline+1,yycolumn+1,yytext());
            }
          case 63: break;
          case 5: 
            { return new java_cup.runtime.Symbol(sym.punto,yyline+1,yycolumn+1,yytext());
            }
          case 64: break;
          case 6: 
            { return new java_cup.runtime.Symbol(sym.parentesisizq,yyline+1,yycolumn+1,yytext());
            }
          case 65: break;
          case 7: 
            { return new java_cup.runtime.Symbol(sym.por,yyline+1,yycolumn+1,yytext());
            }
          case 66: break;
          case 8: 
            { litconst=""; yybegin(constLit);
            }
          case 67: break;
          case 9: 
            { yybegin(comentLlav);
            }
          case 68: break;
          case 10: 
            { return new java_cup.runtime.Symbol(sym.coma,yyline+1,yycolumn+1,yytext());
            }
          case 69: break;
          case 11: 
            { return new java_cup.runtime.Symbol(sym.puntocoma,yyline+1,yycolumn+1,yytext());
            }
          case 70: break;
          case 12: 
            { return new java_cup.runtime.Symbol(sym.igual,yyline+1,yycolumn+1,yytext());
            }
          case 71: break;
          case 13: 
            { return new java_cup.runtime.Symbol(sym.mas,yyline+1,yycolumn+1,yytext());
            }
          case 72: break;
          case 14: 
            { return new java_cup.runtime.Symbol(sym.dospuntos,yyline+1,yycolumn+1,yytext());
            }
          case 73: break;
          case 15: 
            { return new java_cup.runtime.Symbol(sym.mayor,yyline+1,yycolumn+1,yytext());
            }
          case 74: break;
          case 16: 
            { return new java_cup.runtime.Symbol(sym.menor,yyline+1,yycolumn+1,yytext());
            }
          case 75: break;
          case 17: 
            { return new java_cup.runtime.Symbol(sym.parentesisder,yyline+1,yycolumn+1,yytext());
            }
          case 76: break;
          case 18: 
            { return new java_cup.runtime.Symbol(sym.corcheteizq,yyline+1,yycolumn+1,yytext());
            }
          case 77: break;
          case 19: 
            { return new java_cup.runtime.Symbol(sym.corcheteder,yyline+1,yycolumn+1,yytext());
            }
          case 78: break;
          case 20: 
            { 
            }
          case 79: break;
          case 21: 
            { litconst+=yytext();
            }
          case 80: break;
          case 22: 
            { yybegin(YYINITIAL); return new java_cup.runtime.Symbol(sym.constlit,yyline+1,yycolumn+1,litconst);
            }
          case 81: break;
          case 23: 
            { yybegin(comentParFin);
            }
          case 82: break;
          case 24: 
            { yybegin(YYINITIAL);
            }
          case 83: break;
          case 25: 
            { yybegin(comentPar);
            }
          case 84: break;
          case 26: 
            { return new java_cup.runtime.Symbol(sym.puntopunto,yyline+1,yycolumn+1,yytext());
            }
          case 85: break;
          case 27: 
            { return new java_cup.runtime.Symbol(sym.tif,yyline+1,yycolumn+1,yytext());
            }
          case 86: break;
          case 28: 
            { return new java_cup.runtime.Symbol(sym.tdo,yyline+1,yycolumn+1,yytext());
            }
          case 87: break;
          case 29: 
            { return new java_cup.runtime.Symbol(sym.or,yyline+1,yycolumn+1,yytext());
            }
          case 88: break;
          case 30: 
            { return new java_cup.runtime.Symbol(sym.of,yyline+1,yycolumn+1,yytext());
            }
          case 89: break;
          case 31: 
            { return new java_cup.runtime.Symbol(sym.to,yyline+1,yycolumn+1,yytext());
            }
          case 90: break;
          case 32: 
            { return new java_cup.runtime.Symbol(sym.asignacion,yyline+1,yycolumn+1,yytext());
            }
          case 91: break;
          case 33: 
            { return new java_cup.runtime.Symbol(sym.menorigual,yyline+1,yycolumn+1,yytext());
            }
          case 92: break;
          case 34: 
            { return new java_cup.runtime.Symbol(sym.distinto,yyline+1,yycolumn+1,yytext());
            }
          case 93: break;
          case 35: 
            { return new java_cup.runtime.Symbol(sym.mayorigual,yyline+1,yycolumn+1,yytext());
            }
          case 94: break;
          case 36: 
            { litconst+="'";
            }
          case 95: break;
          case 37: 
            { return new java_cup.runtime.Symbol(sym.constnumreal,yyline+1,yycolumn+1,yytext());
            }
          case 96: break;
          case 38: 
            { return new java_cup.runtime.Symbol(sym.end,yyline+1,yycolumn+1,yytext());
            }
          case 97: break;
          case 39: 
            { return new java_cup.runtime.Symbol(sym.not,yyline+1,yycolumn+1,yytext());
            }
          case 98: break;
          case 40: 
            { return new java_cup.runtime.Symbol(sym.div,yyline+1,yycolumn+1,yytext());
            }
          case 99: break;
          case 41: 
            { return new java_cup.runtime.Symbol(sym.and,yyline+1,yycolumn+1,yytext());
            }
          case 100: break;
          case 42: 
            { return new java_cup.runtime.Symbol(sym.mod,yyline+1,yycolumn+1,yytext());
            }
          case 101: break;
          case 43: 
            { return new java_cup.runtime.Symbol(sym.var,yyline+1,yycolumn+1,yytext());
            }
          case 102: break;
          case 44: 
            { return new java_cup.runtime.Symbol(sym.tfor,yyline+1,yycolumn+1,yytext());
            }
          case 103: break;
          case 45: 
            { return new java_cup.runtime.Symbol(sym.telse,yyline+1,yycolumn+1,yytext());
            }
          case 104: break;
          case 46: 
            { return new java_cup.runtime.Symbol(sym.real,yyline+1,yycolumn+1,yytext());
            }
          case 105: break;
          case 47: 
            { return new java_cup.runtime.Symbol(sym.tcase,yyline+1,yycolumn+1,yytext());
            }
          case 106: break;
          case 48: 
            { return new java_cup.runtime.Symbol(sym.type,yyline+1,yycolumn+1,yytext());
            }
          case 107: break;
          case 49: 
            { return new java_cup.runtime.Symbol(sym.then,yyline+1,yycolumn+1,yytext());
            }
          case 108: break;
          case 50: 
            { return new java_cup.runtime.Symbol(sym.begin,yyline+1,yycolumn+1,yytext());
            }
          case 109: break;
          case 51: 
            { return new java_cup.runtime.Symbol(sym.array,yyline+1,yycolumn+1,yytext());
            }
          case 110: break;
          case 52: 
            { return new java_cup.runtime.Symbol(sym.tconst,yyline+1,yycolumn+1,yytext());
            }
          case 111: break;
          case 53: 
            { return new java_cup.runtime.Symbol(sym.twhile,yyline+1,yycolumn+1,yytext());
            }
          case 112: break;
          case 54: 
            { return new java_cup.runtime.Symbol(sym.record,yyline+1,yycolumn+1,yytext());
            }
          case 113: break;
          case 55: 
            { return new java_cup.runtime.Symbol(sym.program,yyline+1,yycolumn+1,yytext());
            }
          case 114: break;
          case 56: 
            { return new java_cup.runtime.Symbol(sym.tint,yyline+1,yycolumn+1,yytext());
            }
          case 115: break;
          case 57: 
            { return new java_cup.runtime.Symbol(sym.function,yyline+1,yycolumn+1,yytext());
            }
          case 116: break;
          case 58: 
            { return new java_cup.runtime.Symbol(sym.procedure,yyline+1,yycolumn+1,yytext());
            }
          case 117: break;
          case 59: 
            { return new java_cup.runtime.Symbol(sym.tchar,yyline+1,yycolumn+1,yytext());
            }
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
